version: '3.7'

name: spark-notebook-package

services:
  spark-notebook-w-package:
    image: jupyter/pyspark-notebook:lab-4.0.7
    container_name: spark-notebook-w-package
    volumes:
      -  "../../jupyter:/home/jovyan/jupyter"
      -  "../../package:/home/jovyan/package"
      -  ../../test_package:/home/jovyan/test_package
      -  ../../data:/home/jovyan/data
      -  ../../setup.py:/home/jovyan/setup.py
    ports:
      -  8888:8888
    command: ["sh", "-c", "pip3 install -e . && start.sh jupyter lab --NotebookApp.token=''"]
