version: '3.7'

name: neo4j

services:
  neo4j:
    image: neo4j:5.25.1
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none
    volumes:
      - neo4j-data:/data
      
volumes:
   neo4j-data:
     name: neo4j-data
